from pathlib import Path


def replace_once(path, old, new):
    target = Path(path)
    text = target.read_text()
    if old not in text:
        raise SystemExit(f"missing expected text in {path}: {old[:120]!r}")
    target.write_text(text.replace(old, new, 1))

replace_once("frontend/lib/domain/contracts.mjs", '  PLATFORM_VARIANT_APPROVAL: "PlatformVariantApproval",\n  CAMPAIGN: "Campaign",', '  PLATFORM_VARIANT_APPROVAL: "PlatformVariantApproval",\n  NARRATIVE_MEMORY: "NarrativeMemory",\n  CAMPAIGN: "Campaign",')
replace_once("frontend/lib/domain/contracts.mjs", '  PlatformVariantApproval: { idField: "platformVariantApprovalId", owner: "workspace", required: ["platformVariantApprovalId", "workspaceId", "platformVariantId", "platformVariantRevisionId", "destination", "decision", "decidedBy", "decidedAt"] },\n  Campaign:', '  PlatformVariantApproval: { idField: "platformVariantApprovalId", owner: "workspace", required: ["platformVariantApprovalId", "workspaceId", "platformVariantId", "platformVariantRevisionId", "destination", "decision", "decidedBy", "decidedAt"] },\n  NarrativeMemory: { idField: "narrativeMemoryId", owner: "workspace", required: ["narrativeMemoryId", "workspaceId", "opportunityId", "narrativeStrategyId", "contentPieceId", "platformVariantId", "platformVariantRevisionId", "platformVariantApprovalId", "platform", "historyStrength", "topic", "angle", "coreIdea", "semanticFingerprint", "approvedAt", "createdAt"] },\n  Campaign:')

replace_once("frontend/tests/domainContracts.test.mjs", '  IdentityProfile: { identityProfileId: "identity-1", workspaceId: "workspace-1", userId: "user-1", version: 1 },', '  NarrativeMemory: {\n    narrativeMemoryId: "memory-1",\n    workspaceId: "workspace-1",\n    opportunityId: "opportunity-1",\n    narrativeStrategyId: "strategy-1",\n    contentPieceId: "piece-1",\n    platformVariantId: "variant-1",\n    platformVariantRevisionId: "variant-revision-1",\n    platformVariantApprovalId: "variant-approval-1",\n    platform: "linkedin",\n    historyStrength: "prepared_internal",\n    topic: "Privacy routing",\n    angle: "Architecture trade-off",\n    coreIdea: "Privacy constraints changed the architecture.",\n    claims: [],\n    evidenceRefs: [],\n    mediaAssetIds: [],\n    lexicalHashes: ["g3:abc12345"],\n    semanticFingerprint: "sf-narrative-v1-test",\n    approvedAt: "2026-08-17T13:15:00.000Z",\n    publishedAt: null,\n    createdAt: "2026-08-17T13:15:00.000Z",\n    updatedAt: "2026-08-17T13:15:00.000Z",\n  },\n  IdentityProfile: { identityProfileId: "identity-1", workspaceId: "workspace-1", userId: "user-1", version: 1 },')

replace_once("frontend/lib/application/platformReviewApplication.mjs", '  identityApplication,\n  inferenceAdapter,', '  identityApplication,\n  narrativeMemoryApplication = null,\n  inferenceAdapter,')
replace_once("frontend/lib/application/platformReviewApplication.mjs", '  if (!identityApplication || typeof identityApplication.evaluateBoundaries !== "function") {\n    throw new TypeError("Platform review requires the Identity application service.");\n  }\n', '  if (!identityApplication || typeof identityApplication.evaluateBoundaries !== "function") {\n    throw new TypeError("Platform review requires the Identity application service.");\n  }\n  if (narrativeMemoryApplication && (typeof narrativeMemoryApplication.recordApprovedVariant !== "function" || typeof narrativeMemoryApplication.removeMemory !== "function")) {\n    throw new TypeError("Narrative memory application must expose recordApprovedVariant() and removeMemory().");\n  }\n')
replace_once("frontend/lib/application/platformReviewApplication.mjs", '  async function sourceForStrategy(strategy) {\n    const storedOpportunity = await opportunities.get(strategy.opportunityId);\n    if (!storedOpportunity) throw new Error(`ContentOpportunity ${strategy.opportunityId} does not exist.`);\n    const opportunity = assertOwned(normalizeContentOpportunity(storedOpportunity));\n    const signalId = opportunity.signalIds?.[0];', '  async function opportunityForStrategy(strategy) {\n    const storedOpportunity = await opportunities.get(strategy.opportunityId);\n    if (!storedOpportunity) throw new Error(`ContentOpportunity ${strategy.opportunityId} does not exist.`);\n    return assertOwned(normalizeContentOpportunity(storedOpportunity));\n  }\n\n  async function sourceForStrategy(strategy) {\n    const opportunity = await opportunityForStrategy(strategy);\n    const signalId = opportunity.signalIds?.[0];')
replace_once("frontend/lib/application/platformReviewApplication.mjs", '  async function approveCurrentVariant(platformVariantId, note = "") {\n    const { variant, revision } = await contextForCurrentVariant(platformVariantId);', '  async function approveCurrentVariant(platformVariantId, note = "") {\n    const { variant, revision, piece, strategy } = await contextForCurrentVariant(platformVariantId);')
replace_once("frontend/lib/application/platformReviewApplication.mjs", '    const now = appClock.now();\n    const approval = await reviews.upsert(createPlatformVariantApproval({\n      platformVariantApprovalId: appIds.create("variant-approval"),\n      workspaceId: ownerWorkspaceId,\n      platformVariantId: variant.platformVariantId,\n      platformVariantRevisionId: revision.platformVariantRevisionId,\n      platformVariantReviewId: review.platformVariantReviewId,\n      destination: variant.destination,\n      decision: APPROVAL_DECISIONS.APPROVED,\n      note,\n      decidedBy: ownerUserId,\n      decidedAt: now,\n    }));\n    await plans.upsert(normalizePlatformVariant({ ...variant, status: VARIANT_STATUSES.APPROVED, updatedAt: now }));\n    return approval;', '    const now = appClock.now();\n    const approvalRecord = createPlatformVariantApproval({\n      platformVariantApprovalId: appIds.create("variant-approval"),\n      workspaceId: ownerWorkspaceId,\n      platformVariantId: variant.platformVariantId,\n      platformVariantRevisionId: revision.platformVariantRevisionId,\n      platformVariantReviewId: review.platformVariantReviewId,\n      destination: variant.destination,\n      decision: APPROVAL_DECISIONS.APPROVED,\n      note,\n      decidedBy: ownerUserId,\n      decidedAt: now,\n    });\n    let derivedMemory = null;\n    if (narrativeMemoryApplication) {\n      const opportunity = await opportunityForStrategy(strategy);\n      derivedMemory = await narrativeMemoryApplication.recordApprovedVariant({ approval: approvalRecord, variant, revision, strategy, contentPiece: piece, opportunity });\n    }\n    let approval;\n    try {\n      approval = await reviews.upsert(approvalRecord);\n    } catch (error) {\n      if (derivedMemory?.narrativeMemoryId && narrativeMemoryApplication) {\n        try { await narrativeMemoryApplication.removeMemory(derivedMemory.narrativeMemoryId); } catch {}\n      }\n      throw error;\n    }\n    await plans.upsert(normalizePlatformVariant({ ...variant, status: VARIANT_STATUSES.APPROVED, updatedAt: now }));\n    return approval;')

replace_once("frontend/lib/application/browserPlatformReviewApplication.mjs", 'import { createIdentityApplication } from "./identityApplication.mjs";\n', 'import { createIdentityApplication } from "./identityApplication.mjs";\nimport { createNarrativeMemoryApplication } from "./narrativeMemoryApplication.mjs";\n')
replace_once("frontend/lib/application/browserPlatformReviewApplication.mjs", 'import { createBrowserIdentityRepository } from "../infrastructure/identityAdapters.mjs";\n', 'import { createBrowserIdentityRepository } from "../infrastructure/identityAdapters.mjs";\nimport { createBrowserNarrativeMemoryRepository } from "../infrastructure/narrativeMemoryAdapters.mjs";\n')
replace_once("frontend/lib/application/browserPlatformReviewApplication.mjs", '  identityKey = "signalflow_identity_profiles_v1",\n', '  identityKey = "signalflow_identity_profiles_v1",\n  narrativeMemoryKey = "signalflow_narrative_memory_v1",\n')
replace_once("frontend/lib/application/browserPlatformReviewApplication.mjs", '  const identityApplication = createIdentityApplication({\n    identityRepository,\n    workspaceId,\n    userId,\n    clock,\n    idService: sharedIds,\n  });\n  return createPlatformReviewApplication({', '  const identityApplication = createIdentityApplication({\n    identityRepository,\n    workspaceId,\n    userId,\n    clock,\n    idService: sharedIds,\n  });\n  const narrativeMemoryApplication = createNarrativeMemoryApplication({\n    narrativeMemoryRepository: createBrowserNarrativeMemoryRepository({ getStorage, key: narrativeMemoryKey }),\n    workspaceId,\n    clock,\n    idService: sharedIds,\n  });\n  return createPlatformReviewApplication({')
replace_once("frontend/lib/application/browserPlatformReviewApplication.mjs", '    identityRepository,\n    identityApplication,\n    inferenceAdapter:', '    identityRepository,\n    identityApplication,\n    narrativeMemoryApplication,\n    inferenceAdapter:')

print("patched NarrativeMemory approval integration")
